### ISSUE TITLE
Why simultaneously releasing 4.0.0 and 5.0.0?

### ISSUE THREAD

**Issue by tschoonj** [libxmlplusplus/libxmlplusplus#20]
Forgive me my ignorance, but why starting two ABI incompatible release series within the hour? When should which release series be used?

Thanks!

**Comment by kjellahl** [comment]
I admit that the difference between 4.0.0 and 5.0.0 should have been explained,
perhaps in the NEWS files or somewhere in the documentation.

4.0.0 is similar to 3.y.z (3.0.0, 3.0.1, 3.2.0, 3.2.2). It uses Glib::ustring,
and therefore has methods that handle UTF-8 characters rather than raw bytes.
The difference between 4.0.0 and 3.y.z is that 4.0.0 depend on the new glibmm-2.68
ABI series, whereas 3.y.z depend on the old glibmm-2.4 ABI series.

5.0.0 does not depend in glibmm. It's not as good at handling UTF-8 strings,
but it has fewer dependencies, which some people appreciate.
See e.g. https://bugzilla.gnome.org/show_bug.cgi?id=320197

**Comment by tschoonj** [comment]
Thanks for the explanation!

**Comment by kjellahl** [comment]
The difference between the libxml++ ABI versions are now briefly explained
at https://libxmlplusplus.github.io/libxmlplusplus/.
