### ISSUE TITLE
version 5.x does not require C++17

### ISSUE THREAD

**Issue by rodolforg** [libxmlplusplus/libxmlplusplus#24]
As far I know, C++ version was ramped up due to glibmm requirements.
As version 5.x does not depend on glibmm anymore (C++17), may I suppose it works with C++11?

Actually, I downloaded 5.0.1 tarball, built it and even did `make check` and everything seems to be ok. But can you confirm it?

**Comment by kjellahl** [comment]
You're right. It's possible to build libxml++ 5.x with a C++11 compiler, and
use it in an application which is built with a C++11 compiler.

Version 5.x was made from version 4.x, which requires C++17 because it
depends on glibmm-2.68. When I released 5.0.0, I decided to pretend that
also version 5.x requires C++17. It gives us the possibility to add code
that requires C++14 or C++17 in the future without breaking API or ABI.
Considering how little maintenance is made on libxml2 and libxml++ these days,
it's unlikely that there will be any significant changes in the next few years.

**Comment by kjellahl** [comment]
> it's unlikely that there will be any significant changes in the next few years.

Unlikely things do happen. Future versions of libxml++ 5.x will require a C++17
compiler. All code that requires C++17 is in .cc files. It might still be
possible to build an application with a C++11 compiler, provided of course that
the application itself only requires C++11.
