### ISSUE TITLE
CI: Windows build problem because of changes in libxml2

### ISSUE THREAD

**Issue by kjellahl** [libxmlplusplus/libxmlplusplus#69]
@talisein The Meson build files in libxml2 have been changed. The CI Windows build
of libxml++ has stopped working. I've tried two modifications of
meson-windows-2022.yml. Both failed to build. Have you got an idea what to do?

**Comment by talisein** [comment]
Fixed in #70 

I tested this in talisein/libxmlplusplus#5. Upstream had a [typo](https://gitlab.gnome.org/GNOME/libxml2/-/merge_requests/272) regarding the python option. And iconv was previously not 'required' since there was no meson build option for it, but now that there's an option we need to set it. Thankfully there's no other flags we need. Minimum would have been nice if it worked.

**Comment by kjellahl** [comment]
Fixed by PR #70
