### ISSUE TITLE
TextReader::get_attribute hides whether the attribute exists

### ISSUE THREAD

**Issue by dbear496** [libxmlplusplus/libxmlplusplus#71]
The `TextReader::get_attribute` methods return an empty string when the attribute does not exist. Unfortunately, this makes it difficult to distinguish between a non-existent attribute and one whose value is the empty string. And a similar issue exists for other methods which return strings.

**Comment by kjellahl** [comment]
The C code in libxml2 uses pointers. Then there's a difference between a `nullptr`
and a pointer to an empty string. C++ programmers don't like raw pointers.

`std::optional<>` would be ideal here. It exists since C++17. Most of the
code in libxml++ was written long before C++17. Now we could have for instance
```
// libxml++4
std::optional<Glib::ustring> get_attribute(const Glib::ustring& name) const;
// libxml++5
std::optional<xmlpp::ustring> get_attribute(const xmlpp::ustring& name) const;
```
Overloaded functions can't differ only in the type of the returned value.
If new functions shall be added that return std::optional, they must have other
names than the existing functions.

**Comment by kjellahl** [comment]
Versions returning `std::optional<ustring>` of the following TextReader methods can be useful:

read_inner_xml(), read_outer_xml(), read_string(), get_base_uri(), get_local_name(),
get_name(), get_namespace_uri(), get_prefix(), get_value(), get_xml_lang(),
get_attribute() (3 overloaded ones), lookup_namespace()

Pull requests are welcome, if they suggest new TextReader methods in libxml++4
and libxml++5.

**Comment by kjellahl** [comment]
Other methods returning `ustring` that can benefit from a version returning `std::optional<ustring>`:

Attribute::get_value(), AttributeDeclaration::get_value(), AttributeNode::get_value(),
ContentNode::get_content(), Document::get_encoding(), Dtd::get_external_id(),
Dtd::get_name(), Dtd::get_system_id(), Element::get_attribute_value(),
EntityDeclaration::get_original_text(), EntityDeclaration::get_resolved_text(),
EntityReference::get_original_text(), EntityReference::get_resolved_text(),
Node::get_name(), Node::get_namespace_prefix(), Node::get_namespace_uri(), Node::get_path().

Methods returning `ustring` which shall not have `std::optional<ustring>` versions:

Document::write_to_string() (throws, if it can't write to a string),
Node::eval_to_string(), Node::eval_xpath() (throw, if they can't evaluate).
